####################################
######## HYPRLAND MENOTAYME ########
####################################


###########################
######## AUTOSTART ########
###########################
exec-once = waybar
exec-once = flameshot
exec-once = discord 
exec-once = /usr/lib/polkit-kde-authentication-agent-1,
exec-once = hyprpaper

###########################
######## DARKMODE  #########
###########################
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark" # for GTK3
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps


env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

cursor {
    no_hardware_cursors = true
}


monitor=DP-3,preferred,auto,1

general {
    gaps_in = 5
    gaps_out = 3
    border_size = 2
    col.active_border = rgb(0f3460)
    col.inactive_border = rgb(45475a)
}

decoration {
    
    rounding = 12

    active_opacity = 0.90
    inactive_opacity = 0.80



    blur {
        enabled = true
        size = 8
        passes = 3
    }
        # Shader to increase saturation
    screen_shader = ~/.config/hypr/shaders/vibrance.glsl
}

# KEYBOARD LANGUAGE
input {
    kb_layout = br
    kb_variant = abnt2
}

# STANDARD EXECUTABLES
$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = hyprlauncher

###########################
######## KEYBINDS #########
###########################


# ESSENTIAL KEYBINDS
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, Escape, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, fullscreen
bind = $mainMod, B, exec, firefox
bind = , Print, exec, flameshot gui
bind = $mainMod, C, exec, code

# SWITCH WINDOW FOCUS USING THE ARROW KEYS
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# CHANGE WORKSPACE
bind = $mainMod, KP_End, workspace, 1
bind = $mainMod, KP_Down, workspace, 2
bind = $mainMod, KP_Next, workspace, 3
bind = $mainMod, KP_Left, workspace, 4
bind = $mainMod, KP_Begin, workspace, 5
bind = $mainMod, KP_Right, workspace, 6
bind = $mainMod, KP_Home, workspace, 7
bind = $mainMod, KP_Up, workspace, 8
bind = $mainMod, KP_Prior, workspace, 9

# MOVE WORKSPACES WINDOWS
bind = $mainMod SHIFT, KP_End, movetoworkspace, 1
bind = $mainMod SHIFT, KP_Down, movetoworkspace, 2
bind = $mainMod SHIFT, KP_Next, movetoworkspace, 3
bind = $mainMod SHIFT, KP_Left, movetoworkspace, 4
bind = $mainMod SHIFT, KP_Begin, movetoworkspace, 5
bind = $mainMod SHIFT, KP_Right, movetoworkspace, 6
bind = $mainMod SHIFT, KP_Home, movetoworkspace, 7
bind = $mainMod SHIFT, KP_Up, movetoworkspace, 8
bind = $mainMod SHIFT, KP_Prior, movetoworkspace, 9

# Window resizing and moving.
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow





